language: cpp
install:
  - cd ~
  - sudo apt-get install build-essential gfortran tcl git m4 freeglut3 doxygen libblas-dev liblapack-dev libx11-dev libnuma-dev libcurl4-gnutls-dev zlib1g-dev libhwloc-dev libxml2-dev libpng-dev pkg-config liblzma-dev
  - wget http://www.mooseframework.org/moose_packages/moose-environment_ubuntu-16.04_20191125_x86_64.deb
  - sudo dpkg -i moose-environment_ubuntu-16.04_20191125_x86_64.deb
  - module load moose-dev-gcc
  - module list
  - git clone https://github.com/hugary1995/moose.git
  - cd moose
  - git checkout next
script:
  - ./scripts/update_and_rebuild_libmesh.sh --with-boost
  - cd test
  - make -j
  - ./run_tests -j
