Content:
    raccoon:
        root_dir: ${ROOT_DIR}/doc/content
    moose:
        root_dir: ${MOOSE_DIR}/framework/doc/content
        content:
            - js/*
            - css/*
            - contrib/**
            - media/**

Renderer:
    type: MooseDocs.base.MaterializeRenderer
    name: RACCOON
    repo: https://github.com/hugary1995/raccoon

Extensions:
    MooseDocs.extensions.navigation:
        name: 'RACCOON'
        repo: https://github.com/hugary1995/raccoon
        home: https://hugary.com/PFFracture
        menu:
            Getting Started: getting_started/index.md
            Examples: examples/index.md
            Theory: theory/index.md
            Documentation: documentation/index.md
    MooseDocs.extensions.appsyntax:
        executable: ${ROOT_DIR}
        includes:
            - include
