# Content:
#   - ${ROOT_DIR}/doc/content
#   - ${MOOSE_DIR}/framework/doc/content
#   - ${MOOSE_DIR}/modules/phase_field/doc/content
#   - ${MOOSE_DIR}/modules/tensor_mechanics/doc/content
#   # - ${MOOSE_DIR}/modules/contact/doc/content
#   # - ${MOOSE_DIR}/modules/heat_conduction/doc/content
#
# Renderer:
#   type: MooseDocs.base.MaterializeRenderer
#   name: RACCOON
#   repo: https://github.com/hugary1995/raccoon
#
# Extensions:
#   MooseDocs.extensions.navigation:
#     name: "RACCOON"
#     repo: https://github.com/hugary1995/raccoon
#     home: https://hugary.dev/raccoon
#     menu:
#       Install: install/index.md
#       Examples: examples/index.md
#       Theory: theory/index.md
#       Documentation: documentation/index.md
#   MooseDocs.extensions.appsyntax:
#     executable: ${ROOT_DIR}
#     hide:
#       framework: !include ${MOOSE_DIR}/framework/doc/hidden.yml
#       phase_field: !include ${MOOSE_DIR}/modules/phase_field/doc/hidden.yml
#       tensor_mechanics: !include ${MOOSE_DIR}/modules/tensor_mechanics/doc/hidden.yml
#       # contact: !include ${MOOSE_DIR}/modules/contact/doc/hidden.yml
#       # heat_conduction: !include ${MOOSE_DIR}/modules/heat_conduction/doc/hidden.yml
#     remove:
#       framework: !include ${MOOSE_DIR}/framework/doc/remove.yml
#   MooseDocs.extensions.common:
#     shortcuts: !include ${MOOSE_DIR}/framework/doc/globals.yml
#   MooseDocs.extensions.acronym:
#     acronyms: !include ${MOOSE_DIR}/framework/doc/acronyms.yml
#   MooseDocs.extensions.sqa:
#     requirement-groups:
#       dgkernels: DGKernel Objects
#       interfacekernels: InterfaceKernel Objects

Content:
  - /home/gary/projects/raccoon/doc/content
  - ${MOOSE_DIR}/framework/doc/content
  - ${MOOSE_DIR}/modules/contact/doc/content
  - ${MOOSE_DIR}/modules/heat_conduction/doc/content
  - ${MOOSE_DIR}/modules/phase_field/doc/content
  - ${MOOSE_DIR}/modules/tensor_mechanics/doc/content
Renderer:
  type: MooseDocs.base.MaterializeRenderer
  name: RACCOON
  repo: https://github.com/hugary1995/raccoon
  home: https://hugary1995.github.io/raccoon

Extensions:
  MooseDocs.extensions.navigation:
    name: "RACCOON"
    repo: https://github.com/hugary1995/raccoon
    home: https://hugary1995.github.io/raccoon
    menu:
      Install: install/index.md
      Examples: examples/index.md
      Theory: theory/index.md
      Documentation: documentation/index.md
  MooseDocs.extensions.appsyntax:
    executable: /home/gary/projects/raccoon
    hide:
      framework: !include ${MOOSE_DIR}/framework/doc/hidden.yml
      contact: !include ${MOOSE_DIR}/modules/contact/doc/hidden.yml
      heat_conduction: !include ${MOOSE_DIR}/modules/heat_conduction/doc/hidden.yml
      phase_field: !include ${MOOSE_DIR}/modules/phase_field/doc/hidden.yml
      tensor_mechanics: !include ${MOOSE_DIR}/modules/tensor_mechanics/doc/hidden.yml
    remove:
      framework: !include ${MOOSE_DIR}/framework/doc/remove.yml
  MooseDocs.extensions.common:
    shortcuts: !include ${MOOSE_DIR}/framework/doc/globals.yml
  MooseDocs.extensions.acronym:
    acronyms: !include ${MOOSE_DIR}/framework/doc/acronyms.yml
  # MooseDocs.extensions.content:
  #   source_links:
  #     action: source/actions/Action.md
  #     actions: source/actions/Action.md
  #     auxkernels: AuxKernels/index.md
  #     bcs: syntax/BCs/index.md
  #     constraints: syntax/Constraints/index.md
  #     controls: syntax/Controls/index.md
  #     dampers: syntax/Dampers/index.md
  #     dgkernels: syntax/DGKernels/index.md
  #     dirackernels: syntax/DiracKernels/index.md
  #     distributions: syntax/Distributions/index.md
  #     executioners: syntax/Executioner/index.md
  #     functions: syntax/Functions/index.md
  #     ics: syntax/ICs/index.md
  #     indicators: syntax/Adaptivity/Indicators/index.md
  #     interfacekernels: syntax/InterfaceKernels/index.md
  #     interfaces: framework_development/interfaces/index.md
  #     kernels: syntax/Kernels/index.md
  #     markers: syntax/Adaptivity/Markers/index.md
  #     materials: syntax/Materials/index.md
  #     mesh: syntax/Mesh/index.md
  #     meshgenerators: syntax/MeshGenerators/index.md
  #     meshmodifiers: syntax/MeshModifiers/index.md
  #     multiapps: syntax/MultiApps/index.md
  #     nodalkernels: syntax/NodalKernels/index.md
  #     outputs: syntax/Outputs/index.md
  #     partitioner: syntax/Mesh/Partitioner/index.md
  #     postprocessors: syntax/Postprocessors/index.md
  #     preconditioners: syntax/Preconditioning/index.md
  #     predictors: syntax/Executioner/Predictor/index.md
  #     problems: syntax/Problem/index.md
  #     restart: application_usage/restart_recover.md
  #     samplers: syntax/Samplers/index.md
  #     scalarkernels: syntax/ScalarKernels/index.md
  #     splits: syntax/Preconditioning/index.md
  #     timeintegrators: syntax/Executioner/TimeIntegrator/index.md
  #     timesteppers: syntax/Executioner/TimeStepper/index.md
  #     transfers: syntax/Transfers/index.md
  #     userobject: syntax/UserObjects/index.md
  #     userobjects: syntax/UserObjects/index.md
  #     utils: framework_development/utils/index.md
  #     variables: syntax/Variables/index.md
  #     vectorpostprocessors: syntax/VectorPostprocessors/index.md
  MooseDocs.extensions.template:
    active: True
  MooseDocs.extensions.sqa:
    active: True
    categories:
      framework: !include ${MOOSE_DIR}/framework/doc/sqa_framework.yml
      tensor_mechanics: !include ${MOOSE_DIR}/modules/tensor_mechanics/doc/sqa_tensor_mechanics.yml
      contact: !include ${MOOSE_DIR}/modules/contact/doc/sqa_contact.yml
      heat_conduction: !include ${MOOSE_DIR}/modules/heat_conduction/doc/sqa_heat_conduction.yml
      phase_field: !include ${MOOSE_DIR}/modules/phase_field/doc/sqa_phase_field.yml

    requirement-groups:
      dgkernels: DGKernel Objects
      interfacekernels: InterfaceKernel Objects
