Content:
    - ${ROOT_DIR}/doc/content
    - ${MOOSE_DIR}/framework/doc/content
    - ${MOOSE_DIR}/modules/phase_field/doc/content
    - ${MOOSE_DIR}/modules/tensor_mechanics/doc/content

Renderer:
    type: MooseDocs.base.MaterializeRenderer
    name: RACCOON
    repo: https://github.com/hugary1995/raccoon

Extensions:
    MooseDocs.extensions.navigation:
        name: 'RACCOON'
        repo: https://github.com/hugary1995/raccoon
        home: https://hugary.com/raccoon
        menu:
            Getting Started: getting_started/index.md
            Examples: examples/index.md
            Theory: theory/index.md
            Documentation: documentation/index.md
    MooseDocs.extensions.appsyntax:
        executable: ${ROOT_DIR}
        hide:
            framework: !include ${MOOSE_DIR}/framework/doc/hidden.yml
            phase_field: !include ${MOOSE_DIR}/modules/phase_field/doc/hidden.yml
            tensor_mechanics: !include ${MOOSE_DIR}/modules/tensor_mechanics/doc/hidden.yml
        remove:
            framework: !include ${MOOSE_DIR}/framework/doc/remove.yml
    MooseDocs.extensions.common:
        shortcuts: !include ${MOOSE_DIR}/framework/doc/globals.yml
    MooseDocs.extensions.acronym:
        acronyms: !include ${MOOSE_DIR}/framework/doc/acronyms.yml
    MooseDocs.extensions.sqa:
        requirement-groups:
            dgkernels: DGKernel Objects
            interfacekernels: InterfaceKernel Objects
