name: Merge devel into master
on:
  schedule:
    - cron: '0,10,20,30,40,50 0 * * *'
jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Merge devel into master
        run: |
          git config user.name 'Gary Hu'
          git config user.email '31555204+hugary1995@users.noreply.github.com'
          git merge-base HEAD origin/devel
          git merge --no-ff origin/devel
          git push
